module.exports = {
  extends: ['airbnb/base', 'prettier'],
  env: {
    browser: true,
    node: true,
  },
  plugins: [
    'prettier',
    'prettier/flowtype',
    'flowtype',
    'flowtype-errors',
    'plugin:flowtype/recommended',
  ],
  rules: {
    semi: 0,
    'arrow-parens': 0,
    'class-methods-use-this': 0,
    curly: [2, 'multi-line'],
    'flowtype-errors/enforce-min-coverage': [2, 70],
    'flowtype-errors/show-errors': 2,
    'flowtype/boolean-style': [2, 'boolean'],
    'flowtype/no-dupe-keys': 2,
    'flowtype/object-type-delimiter': 2,
    'flowtype/require-valid-file-annotation': [
      2,
      'always',
      { annotationStyle: 'line' },
    ],
    'import/extensions': ['error', 'never', { packages: 'always' }],
    'import/no-extraneous-dependencies': 0,
    'import/no-named-as-default': [0],
    'no-confusing-arrow': 0,
    'no-duplicate-imports': 0,
    'no-else-return': 0,
    'no-prototype-builtins': 0,
    'no-unused-vars': [2, { varsIgnorePattern: '^_+$' }],
    'no-unused-expressions': ['error', { allowTaggedTemplates: true }],
    quotes: 0,
    'prettier/prettier': 2,
    'symbol-description': 0,
  },
  globals: {
    SyntheticEvent: true,
    SyntheticAnimationEvent: true,
    SyntheticClipboardEvent: true,
    SyntheticCompositionEvent: true,
    SyntheticInputEvent: true,
    SyntheticUIEvent: true,
    SyntheticFocusEvent: true,
    SyntheticKeyboardEvent: true,
    SyntheticMouseEvent: true,
    SyntheticDragEvent: true,
    SyntheticWheelEvent: true,
    SyntheticTouchEvent: true,
    SyntheticTransitionEvent: true,
  },
};
